# Generated by Django 3.0.5 on 2020-05-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200504_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoodInstance',
            new_name='BookInstance',
        ),
    ]
