# Generated by Django 3.0.5 on 2020-05-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200511_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langueage',
            new_name='language',
        ),
    ]
